# Generated by Django 4.2.6 on 2023-10-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compain_and_notification', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complain',
        ),
    ]
